# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Baguette studio blog
email: hello@unebaguette.com
description: > # this means to ignore newlines until "baseurl:"
  Baguette team writes about web design, development, project management and other exciting things.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http:/blog.unebaguette.com" # the base hostname & protocol for your site
twitter_username: arturi
github_username:  arturi

# Build settings
markdown: kramdown
